export const STANDARD_MESSAGES = {
  FETCH_SUCCESS: "FETCH_SUCCESS",
  CREATE_SUCCESS: "CREATE_SUCCESS",
  UPDATE_SUCCESS: "UPDATE_SUCCESS",
  DELETE_SUCCESS: "DELETE_SUCCESS",
  NOT_FOUND: "NOT_FOUND",
  BAD_REQUEST: "BAD_REQUEST",
  SERVER_ERROR: "SERVER_ERROR",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
};

/**
 * @typedef {'FETCH_SUCCESS' | 'CREATE_SUCCESS' | 'UPDATE_SUCCESS' | 'DELETE_SUCCESS' | 
 * 'NOT_FOUND' | 'BAD_REQUEST' | 'SERVER_ERROR' | 'UNAUTHORIZED' | 'FORBIDDEN'} StandardMessage
 */